site_name: IoT

nav:
  - Home: index.md
  - instalação: guias/instalacao.md
  - Aulas: 
    - Aula01: aulas/aula01/Aula1-Intro IA-IoT-2021.pdf
    - Aula02: aulas/aula02/Aula2-IoT-22.pdf

theme: material
