site_name: IoT

nav:
  - Home: index.md
  - Instalação: guias/instalacao.md
  - Laboratórios: 
    - Lab01: aulas/lab1/Aula1-IoT-22.pdf
    - Lab02: aulas/lab2/Aula2-IoT-22.pdf
    - Lab03: aulas/lab3/Aula3-IoT-22.pdf
  - Exemplos: 
    - Jogo da memória: aulas/lab3/jogomemoria/jogomemoria.ino
  - Dicas: 
    - Cheat Sheet: aulas/Dicas/Arduino-Cheat-Sheet.pdf
    
theme: material
